drop table sample_annotation;
drop table sample_annotation_biomaterial;
drop table sample_annotation_genotyping;
drop table sample_annotation_solid;
drop table sample_annotation_hiseq;
drop table sample_annotation_others;

create table sample_annotation (
   biomaterial_id        varchar(100) not null, 
   biomaterial_name      varchar(100), 
   subject_id            varchar(100), 
   person_id             varchar(100),
   person                varchar(100),
   type_sequencing       varchar(100),
   type_seq              varchar(100),
   library_name          varchar(100),
   solid_run_name        varchar(100), 
   file_name             varchar(100), 
   library_id            varchar(100),
   fcid                  varchar(100)
);

create table sample_annotation_biomaterial(
   biomaterial_id        varchar(100) not null,      
   anatomy_celltype      varchar(100),
   concentration         varchar(100),
   current_mass          varchar(100),
   current_volume        varchar(100),
   current_status        varchar(100),
   date1                 varchar(100),
   date2                 varchar(100),
   initial_mass          varchar(100),
   initial_volume        varchar(100),
   biomaterial_name      varchar(100),
   notes                 varchar(1000),
   source_biomaterial_id varchar(100),
   sample_quality        varchar(100),
   subject_id            varchar(100),
   btype                 varchar(100),
   diagnosis             varchar(100),
   bproject              varchar(100),
   custom_id             varchar(100),
   is_proband            varchar(100),
   study_code            varchar(100),
   subject_notes         varchar(1000),
   person_id             varchar(100),
   person                varchar(100),
   anonymous             varchar(100),
   mortality_status      varchar(100),
   sex                   varchar(100),
   type_sequencing       varchar(100),
   dnarna_extracted      varchar(100),
   dna_wga               varchar(100),
   note2_paper           varchar(100)
);

create table sample_annotation_genotyping(
   biomaterial_id        varchar(100) not null,      
   finger_printing       varchar(100),
   str_lab               varchar(100),
   str_date              varchar(100),
   notes                 varchar(100),
   amel_1                varchar(100),
   amel_2                varchar(100),
   csf1po_1              varchar(100),
   csf1po_2              varchar(100),
   d13s317_1             varchar(100),
   d13s317_2             varchar(100),
   d16s539_1             varchar(100),
   d16s539_2             varchar(100),
   d18s51_1              varchar(100),
   d18s51_2              varchar(100),
   d19s433_1             varchar(100),
   d19s433_2             varchar(100),
   d21s11_1              varchar(100),
   d21s11_2              varchar(100),
   d2s1338_1             varchar(100),
   d2s1338_2             varchar(100),
   d3s1358_1             varchar(100),
   d3s1358_2             varchar(100),
   d5s818_1              varchar(100),
   d5s818_2              varchar(100),
   d7s820_1              varchar(100),
   d7s820_2              varchar(100),
   d8s1179_1             varchar(100),
   d8s1179_2             varchar(100),
   fga_1                 varchar(100),
   fga_2                 varchar(100),
   th01_1                varchar(100),
   th01_2                varchar(100),
   tpox_1                varchar(100),
   tpox_2                varchar(100),
   vwa_1                 varchar(100),
   vwa_2                 varchar(100)
);                       
                         
create table sample_annotation_solid(
   biomaterial_id        varchar(100) not null,      
   dna_used_in_library   varchar(100),                  
   multiplex_or_single   varchar(100),                  
   exome_37or100mb       varchar(100),
   pull_down             varchar(100),
   rnaseq_library_method varchar(100),                    
   type_seq              varchar(100),
   library_name          varchar(100),
   solid_run_name        varchar(100),
   solid_version         varchar(100),
   flowcell_sequenced    varchar(100),                 
   bioinfo_pipeline      varchar(100),
   bioinfo_operater      varchar(100)
);                       
                         
create table sample_annotation_hiseq(
   biomaterial_id               varchar(100) not null,      
   hiseq_exome_rnaseq_run       varchar(100),
   seq_lab                      varchar(100),
   hiseq_rnaseq_library         varchar(100),
   batch_number                 varchar(100),
   machine                      varchar(100),
   run_start_date               varchar(100),
   run_finish_date              varchar(100),
   flow_cell_posteosarcomaition varchar(100),                   
   fcid                         varchar(100),
   lane                         varchar(100),
   library_id                   varchar(100),
   sampleref                    varchar(100),
   hindex                       varchar(100),
   description                  varchar(100),
   control                      varchar(100),
   recipe                       varchar(100),
   hoperator                    varchar(100),
   sampleproject                varchar(100),
   multiplex_id                 varchar(100),
   pe                           varchar(100),
   seq_kit                      varchar(100),
   read1                        varchar(100),
   read2                        varchar(100),
   yield_per_lane               varchar(100),
   hreads                       varchar(100),
   hindex2                      varchar(100),
   potion_q30bases              varchar(100),
   mean_quality                 varchar(100),
   cbot_lib_con                 varchar(100),
   hcluster                     varchar(100),
   passed_filter_cluster        varchar(100),
   lib_prep_batch               varchar(100),
   qpcr_date                    varchar(100),
   comments                     varchar(100),
   quality_summary              varchar(100),
   seq_lab2                     varchar(100),
   location_data                varchar(100),
   location_qcfile              varchar(100),
   rerun                        varchar(100),
   lanes                        varchar(100),
   bioinfo_pipeline             varchar(100),
   bioinfo_operater             varchar(100)
);                              

create table sample_annotation_others(
   biomaterial_id              varchar(100) not null,      
   snp_or_array                varchar(100),
   file_name                   varchar(100),
   methylation                 varchar(100),
   methylation_infinium_file   varchar(100),                      
   ion_pgm                     varchar(100),
   dna_used_in_ampliseq        varchar(100)
);                            

